### PR TITLE
prevent boundary start index from being too big

### LINKED ISSUE #6: thread 'main' panicked at 'slice index starts at 8193 but ends at 8192'
I get the error above when I try to process a multipart form. This is with the current master branch, hyper 0.11.7, and Rust nightly-2017-10-05.

The bracktrace points to the following lines:

```
13: <multipart_async::server::boundary::BoundaryFinder<S>>::body_chunk
             at /home/jacob/.cargo/git/checkouts/multipart-async-60cdbbbb5190592f/2dd43a5/src/server/boundary.rs:113
14: <multipart_async::server::boundary::BoundaryFinder<S>>::consume_boundary
             at /home/jacob/.cargo/git/checkouts/multipart-async-60cdbbbb5190592f/2dd43a5/src/server/boundary.rs:220
```

### PR DESCRIPTION
**Pull request by kardeiz**
This seems to fix #6 for me, but it's a naive solution; I don't fully understand everything that is going on here.

### CODE REVIEW

**Comment by abonander** [comment]
I would actually check why `res.boundary_start()` is greater than the slice length, there's probably an off-by-one error in that method. It's been a while since I looked at this code but I can probably figure it out if you have trouble.

**Comment by kierdavis** [comment]
I've just had a quick glance over this. Maybe the reason why `res.boundary_start()` is sometimes greater than the slice length is because [under some conditions it adds 2 to the boundary start index](https://github.com/abonander/multipart-async/blob/master/src/server/boundary.rs#L356). E.g. if `res.idx == 8191` (presumably valid?) and `res.incl_crlf` is true, `res.boundary_start()` would return 8193 and hence causes a panic in `body_chunk`. I haven't understood the code in enough detail to know if this is the case or not, however.

**Comment by abonander** [comment]
@kierdavis It's been a while since I've looked at this repo cause I've been waiting for the Futures/Tokio dust to settle. That's a good hypothesis; if I remember correctly if the boundary isn't found the search returns the length of the buffer so that returning `buf[..res.boundary_start()]` is correct, and thus adding two to that would push it out-of-bounds.

I think the correct fix would be to bump the index for the `incl_crlf` case when the `SearchResult` is created and not in the `boundary_start()` getter, which could then be deleted and just use `res.idx` directly. This library also *desperately* needs more tests written for it, I think this case would be a good start since it's actually kind of a common one.

**Comment by abonander** [comment]
I've found and fixed several boundary bugs on master during my refactoring, please reopen this if it is still an issue.

**Pull request closed without merging**
